### PR TITLE
Make package public and update links for NPM

### LINKED ISSUE #400: Link github on npm
i think its due to the private property in the package.json - makes it quite a lot harder to dfind the repo

### PR DESCRIPTION
**Pull request by PadraigGalvin**
Fixes #400

### CODE REVIEW

**Comment by princemaple** [comment]
Might be a good idea to merge this before making a release @werthdavid

**Comment by princemaple** [comment]
Will a release be made soon?

**Comment by werthdavid** [comment]
Can you verify everything works as expected with angular 12?

**Comment by princemaple** [comment]
What's the best way to check? I do have some doubt about having exact angular versions in the package.json. I think they should be prefixed with `^` or `~` to avoid version lock in for users.

**Comment by princemaple** [comment]
I realized that the version requirement published to npm is different from the version requirement from the project. I'll give the project demo a go.

**Comment by princemaple** [comment]
Please see #411 

Also this PR #410 is kinda irrelevant as it's changing the project root package json which isn't published.

**Pull request merged**
